#!/usr/bin/env bash

DIR="/home/jhxnnat/Dev/scripts"

usage () {
    echo "Usage:  Init [desktop]"
	echo "  - desktop: h (Hyprland), i (i3wm), k (KDE), x (xfce), g (gnome)"
}

hyprland () {
    echo "Getting into Hyprland..."
    Hyprland
}

i3wm () {
    echo "Getting into i3wm..."
    cat "$DIR/i3wm.txt" > "$HOME/.xinitrc"
    startx
}

kde () {
    echo "Getting into KDE..."
    cat "$DIR/kde.txt" > "$HOME/.xinitrc"
    startx
}

xfce () {
    echo "Getting into xfce..."
    cat "$DIR/xfce.txt" > "$HOME/.xinitrc"
    startx
}

gnome () {
    echo "Getting into Gnome..."
	XDG_SESSION_TYPE=wayland dbus-run-session gnome-session
}

cinnamon () {
	echo "Getting into Cinnamon..."
    cat "$DIR/cinnamon.txt" > "$HOME/.xinitrc"
	startx
}

if [ $# -eq 0 ]; then
    usage
else 
    case $1 in
        'h') echo 'Hypr...';;
        'i') i3wm;;
        # 'k') kde;;
		# 'g') gnome;;
        'x') xfce;;
        'c') cinnamon;;
        *) usage;;
    esac
fi

